# coding: utf-8

"""
    tagbase-server API

    tagbse-server provides HTTP endpoints for ingestion of various files \\ into a Tagbase SQL database. Input file support currently includes eTUFF (see [here](https://doi.org/10.6084/m9.figshare.10032848.v4) \\ and [here](https://doi.org/10.6084/m9.figshare.10159820.v1)). The REST API complies with [OpenAPI v3.0.3](https://spec.openapis.org/oas/v3.0.3.html). 

    The version of the OpenAPI document: v0.14.0
    Contact: tagtuna@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pytagbase.api.tags_api import TagsApi  # noqa: E501


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_sub(self) -> None:
        """Test case for delete_sub

        Delete a tag submission  # noqa: E501
        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete an individual tag  # noqa: E501
        """
        pass

    def test_delete_tags(self) -> None:
        """Test case for delete_tags

        Delete all tags  # noqa: E501
        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        Get information about an individual tag  # noqa: E501
        """
        pass

    def test_list_tags(self) -> None:
        """Test case for list_tags

        Get information about all tags  # noqa: E501
        """
        pass

    def test_replace_tag(self) -> None:
        """Test case for replace_tag

        Update the 'notes' and/or 'version' associated with a tag submission  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
