# coding: utf-8

"""
    tagbase-server API

    tagbse-server provides HTTP endpoints for ingestion of various files \\ into a Tagbase SQL database. Input file support currently includes eTUFF (see [here](https://doi.org/10.6084/m9.figshare.10032848.v4) \\ and [here](https://doi.org/10.6084/m9.figshare.10159820.v1)). The REST API complies with [OpenAPI v3.0.3](https://spec.openapis.org/oas/v3.0.3.html). 

    The version of the OpenAPI document: v0.14.0
    Contact: tagtuna@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pytagbase.api.ingest_api import IngestApi  # noqa: E501


class TestIngestApi(unittest.TestCase):
    """IngestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IngestApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_ingest_get(self) -> None:
        """Test case for ingest_get

        Get network accessible file and execute ingestion  # noqa: E501
        """
        pass

    def test_ingest_post(self) -> None:
        """Test case for ingest_post

        Post a local file and perform a ingest operation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
