# coding: utf-8

# flake8: noqa

"""
    tagbase-server API

    tagbse-server provides HTTP endpoints for ingestion of various files \\ into a Tagbase SQL database. Input file support currently includes eTUFF (see [here](https://doi.org/10.6084/m9.figshare.10032848.v4) \\ and [here](https://doi.org/10.6084/m9.figshare.10159820.v1)). The REST API complies with [OpenAPI v3.0.3](https://spec.openapis.org/oas/v3.0.3.html). 

    The version of the OpenAPI document: v0.14.0
    Contact: tagtuna@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# import apis into sdk package
from pytagbase.api.ingest_api import IngestApi
from pytagbase.api.tags_api import TagsApi

# import ApiClient
from pytagbase.api_response import ApiResponse
from pytagbase.api_client import ApiClient
from pytagbase.configuration import Configuration
from pytagbase.exceptions import OpenApiException
from pytagbase.exceptions import ApiTypeError
from pytagbase.exceptions import ApiValueError
from pytagbase.exceptions import ApiKeyError
from pytagbase.exceptions import ApiAttributeError
from pytagbase.exceptions import ApiException

# import models into sdk package
from pytagbase.models.error import Error
from pytagbase.models.error_container import ErrorContainer
from pytagbase.models.ingest200 import Ingest200
from pytagbase.models.tag import Tag
from pytagbase.models.tag200 import Tag200
from pytagbase.models.tag_put200 import TagPut200
from pytagbase.models.tag_submission import TagSubmission
from pytagbase.models.tags200 import Tags200
